charity/urls.py
from django.urls import path
from . import views

app_name = 'charity'

urlpatterns = [
    path('register/', views.register, name='registration'),
    path('login/', views.login_user, name='login'),
    path('', views.landingpage, name='landingpage'),
    path('donation/', views.donation, name='donation'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('<int:donation_id>/take/', views.take_donation, name='take_donation'),
    path('<int:donation_id>/return/', views.return_donation, name='return_donation'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('charity.urls')),
]

if settings.DEBUG:
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

charity/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


choices = [('fundacja', 'Fundacja'),
           ('organizacja_pozarzadowa', 'Organizacja pozarządowa'),
           ('zbiorka_lokalna', 'Zbiórka lokalna')]


class Institution(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    type = models.CharField(max_length=30, choices=choices, default= 'fundacja')
    categories = models.ManyToManyField(Category)

    class Meta:
        permissions = [
            ("can_manage_institutions", "Can manage institutions"),
        ]

    def __str__(self):
        return self.name


class Donation(models.Model):
    quantity = models.IntegerField()
    categories = models.ManyToManyField(Category)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    address = models.CharField(max_length=250)
    phone_number = models.CharField(max_length=50)
    city = models.CharField(max_length=250)
    zip_code = models.CharField(max_length=50)
    pick_up_date = models.DateField()
    pick_up_time = models.TimeField(null=True)
    pick_up_comment = models.TextField()
    user = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    is_taken = models.BooleanField(default=False)

charity/forms.py
from django import forms
from django.forms import PasswordInput


class EditProfileForm(forms.Form):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=254, required=False)
    password = forms.CharField(widget=PasswordInput(), required=True)

charity/views.py
from . import models
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from .forms import EditProfileForm
from .models import Donation


def landingpage(request):
    return render(request, "charity/index.html", {'donations_all': models.Donation.objects.all().count(),
                                                  'organisations_all': models.Donation.objects.values('institution').distinct().count(),
                                                  'institutions': models.Institution.objects.all(),
                                                  'categories': models.Category.objects.all(),
                                                  'institution_categories': models.Institution.categories.through.objects.all()})


@login_required(login_url='/login/')
def donation(request):
    return render(request, "charity/form.html", {'categories': models.Category.objects.all(),
                                                 'institutions': models.Institution.objects.all(),
                                                 'institution_categories': models.Institution.categories.through.objects.all(),})


def login_user(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            return redirect('/register/')
    else:
        return render(request, "charity/login.html")


def logout_user(request):
    logout(request)
    return redirect('/')


def register(request):
    if request.method == 'POST':
        # Extract form data
        name = request.POST['name']
        surname = request.POST['surname']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']

        # Create new user
        user = User.objects.create_user(
            username=email,
            email=email,
            password=password,
            first_name=name,
            last_name=surname
        )

        # Redirect to login page
        return redirect('/login/')
    else:
        return render(request, 'charity/register.html')


def user_profile(request):
    return render(request, 'charity/user_profile.html', {'user': request.user,
                                                         'donations':models.Donation.objects.all(),})


@login_required
def edit_profile(request):
    user = request.user
    if request.method == 'POST':
        form = EditProfileForm(request.POST)
        if form.is_valid():
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            if user.check_password(password):
                user.save()
                return redirect('/profile/')
            else:
                form.add_error('password', 'Incorrect password')
    else:
        form = EditProfileForm(initial={
            'first_name': user.first_name,
            'last_name': user.last_name,
            'email': user.email
        })
    context = {'form': form}
    return render(request, 'charity/edit_profile.html', context)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('/profile/')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'charity/change_password.html', {'form': form})


def take_donation(request, donation_id):
    donation = get_object_or_404(Donation, id=donation_id)

    if request.method == 'POST':
        donation.is_taken = True
        donation.save()
        return redirect('/profile/')


def return_donation(request, donation_id):
    donation = get_object_or_404(Donation, id=donation_id)

    if request.method == 'POST':
        donation.is_taken = False
        donation.save()
        return redirect('/profile/')

charity/templates/charity/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block container %}

<style>
    h1 {
        text-align: center;
    }
    /* Style form inputs */
input[type="password"] {
    display: flex;
    border: 1px solid #ccc;
    padding: 8px;
    max-width: 300px;
    width: 100%;
    margin-bottom: 10px;
    flex-direction: column;
    align-items: center;

}

/* Style form labels */
label {

    margin-bottom: 8px;
    font-size: 16px;
    font-weight: bold;
    display: flex;
    flex-direction: column;
    align-items: center;
    }

/* Style form buttons */
button {
    padding: 8px 16px;
    border-radius: 5px;
    cursor: pointer;
    align-items: center;
    font-size: 20px;

}
/* Add some spacing between form elements */
form > * {
    margin-top: 20px;
    margin-bottom: 20px;
    display: flex;
    flex-direction: column;
    align-items: center;
}
form {
    display: flex;
    flex-direction: column;
    align-items: center;
    }



</style>
  <h1>Change Password</h1>
  <form method="POST" action="{% url 'charity:change_password' %}">
    {% csrf_token %}
    {{ form.old_password|as_crispy_field }}
    {{ form.new_password1|as_crispy_field }}
    {{ form.new_password2|as_crispy_field }}
    <button type="submit" class="btn btn-primary">Zmień Hasło</button>
  </form>
{% endblock %}

charity/templates/charity/edit_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block container %}
    <header>{% include 'partials/nav.html' %}</header>
  <h2>Edit Profile</h2>
  <form method="post" action="">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Update Profile</button>
    <a class="btn btn-primary" href="{% url 'charity:change_password' %}" >Zmień hasło</a>
  </form>
{% endblock %}

charity/templates/charity/form-confirmation.html
{% extends 'base.html' %}
{% load static %}

{% block container %}
<body>
    <header class="header--form-page">
        {% include 'partials/nav.html' %}

      <div class="slogan container container--90">
          <h2>
            Dziękujemy za przesłanie formularza Na maila prześlemy wszelkie
            informacje o odbiorze.
          </h2>
      </div>
    </header>

    <footer>
      <div id="contact" class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
          <div class="form-group form-group--50">
            <input type="text" name="name" placeholder="Imię" />
          </div>
          <div class="form-group form-group--50">
            <input type="text" name="surname" placeholder="Nazwisko" />
          </div>

          <div class="form-group">
            <textarea
              name="message"
              placeholder="Wiadomość"
              rows="1"
            ></textarea>
          </div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2018</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"
            ><img src="/static/images/icon-facebook.svg"
          /></a>
          <a href="#" class="btn btn--small"
            ><img src="/static/images/icon-instagram.svg"
          /></a>
        </div>
      </div>
    </footer>

    <script src="/static/js/app.js"></script>
  </body>
{% endblock %}

charity/templates/charity/form.html
{% extends 'base.html' %}
{% load static %}

{% block container %}
  <body>
    <header class="header--form-page">
        {% include 'partials/nav.html' %}
      <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Oddaj rzeczy, których już nie chcesz<br />
            <span class="uppercase">potrzebującym</span>
          </h1>

          <div class="slogan--steps">
            <div class="slogan--steps-title">Wystarczą 4 proste kroki:</div>
            <ul class="slogan--steps-boxes">
              <li>
                <div><em>1</em><span>Wybierz rzeczy</span></div>
              </li>
              <li>
                <div><em>2</em><span>Spakuj je w worki</span></div>
              </li>
              <li>
                <div><em>3</em><span>Wybierz fundację</span></div>
              </li>
              <li>
                <div><em>4</em><span>Zamów kuriera</span></div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </header>

    <section class="form--steps">
      <div class="form--steps-instructions">
        <div class="form--steps-container">
          <h3>Ważne!</h3>
          <p data-step="1" class="active">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="2">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="3">
           Wybierz jedną, do
            której trafi Twoja przesyłka.
          </p>
          <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
        </div>
      </div>

      <div class="form--steps-container">
        <div class="form--steps-counter">Krok <span>1</span>/5</div>

        <form action="form-confirmation.html" method="post">
          <!-- STEP 1: class .active is switching steps -->
          <div data-step="1" class="active">
            <h3>Zaznacz co chcesz oddać:</h3>

            {% for category in categories %}
            <div class="form-group form-group--checkbox">
              <label>
                <input
                  type="checkbox"
                  name= {{ category.name }}
                  value= {{ category.id }}
                />
                <span class="checkbox"></span>
                <span class="description"
                  >{{ category.name }}</span
                >
              </label>
            </div>
            {% endfor %}

            <div class="form-group form-group--buttons">
              <button type="button" class="btn next-step" id="category-btn">Dalej</button>
            </div>
          </div>

          <!-- STEP 2 -->
          <div data-step="2">
            <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>

            <div class="form-group form-group--inline">
              <label>
                Liczba 60l worków:
                <input type="number" name="bags" step="1" min="1" />
              </label>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>



          <!-- STEP 4 -->
          <div data-step="3">
            <h3>Wybierz organizacje, której chcesz pomóc:</h3>
            {% for institution in institutions %}
                    <div class="form-group form-group--checkbox">
                      <label>
                        <input type="radio" name="organization" value="{{ institution.id }}"/>
                        <span class="checkbox radio"></span>
                        <span class="description">
                          <span class="title">{{ institution.name }}</span>
                          <span class="subtitle">
                            Cel i misja: Pomoc dla osób nie posiadających miejsca
                            zamieszkania
                          </span>
                        </span>
                      </label>
                    </div>
            {% endfor %}
            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 5 -->
          <div data-step="4">
            <h3>Podaj adres oraz termin odbioru rzecz przez kuriera:</h3>

            <div class="form-section form-section--columns">
              <div class="form-section--column">
                <h4>Adres odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Ulica <input type="text" name="address" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Miasto <input type="text" name="city" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Kod pocztowy <input type="text" name="postcode" />
                  </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Numer telefonu <input type="phone" name="phone" />
                  </label>
                </div>
              </div>

              <div class="form-section--column">
                <h4>Termin odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Data <input type="date" name="data" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Godzina <input type="time" name="time" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Uwagi dla kuriera
                    <textarea name="more_info" rows="5"></textarea>
                  </label>
                </div>
              </div>
            </div>
            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 6 -->
          <div data-step="5">
            <h3>Podsumowanie Twojej darowizny</h3>

            <div class="summary">
              <div class="form-section">
                <h4>Oddajesz:</h4>
                <ul>
                  <li>
                    <span class="icon icon-bag"></span>
                    <span class="summary--text"
                      >4 worki ubrań w dobrym stanie dla dzieci</span
                    >
                  </li>

                  <li>
                    <span class="icon icon-hand"></span>
                    <span class="summary--text"
                      >Dla fundacji "Mam marzenie" w Warszawie</span
                    >
                  </li>
                </ul>
              </div>

              <div class="form-section form-section--columns">
                <div class="form-section--column">
                  <h4>Adres odbioru:</h4>
                  <ul>
                    <li>Prosta 51</li>
                    <li>Warszawa</li>
                    <li>99-098</li>
                    <li>123 456 789</li>
                  </ul>
                </div>

                <div class="form-section--column">
                  <h4>Termin odbioru:</h4>
                  <ul>
                    <li>13/12/2018</li>
                    <li>15:40</li>
                    <li>Brak uwag</li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="submit" class="btn">Potwierdzam</button>
            </div>
          </div>
        </form>
      </div>
    </section>

    <footer>
      <div id="contact" class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
          <div class="form-group form-group--50">
            <input type="text" name="name" placeholder="Imię" />
          </div>
          <div class="form-group form-group--50">
            <input type="text" name="surname" placeholder="Nazwisko" />
          </div>

          <div class="form-group">
            <textarea
              name="message"
              placeholder="Wiadomość"
              rows="1"
            ></textarea>
          </div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2018</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"
            ><img src="/static/images/icon-facebook.svg"
          /></a>
          <a href="#" class="btn btn--small"
            ><img src="/static/images/icon-instagram.svg"
          /></a>
        </div>
      </div>
    </footer>

    <script src="/static/js/app.js"></script>
  </body>
{% endblock %}

charity/templates/charity/login.html
{% extends 'base.html' %}
{% load static %}
{% block container %}
    <header>{% include 'partials/nav.html' %}</header>
  <body>
    <section class="login-page">
      <h2>Zaloguj się</h2>
      <form method="POST" action="/login/">
        {% csrf_token %}
        <div class="form-group">
          <input type="email" name="email" placeholder="Email" />
        </div>
        <div class="form-group">
          <input type="password" name="password" placeholder="Hasło" />
          <a href="#" class="btn btn--small btn--without-border reset-password">Przypomnij hasło</a>
        </div>

        <div class="form-group form-group--buttons">
          <a href="#" class="btn btn--without-border">Załóż konto</a>      
          <button class="btn" type="submit">Zaloguj się</button> 
        </div>
      </form>
    </section>

    <footer>
        <div id="contact" class="contact">
          <h2>Skontaktuj się z nami</h2>
          <h3>Formularz kontaktowy</h3>
          <form>
            <div class="form-group form-group--50">
              <input type="text" name="name" placeholder="Imię" />
            </div>
            <div class="form-group form-group--50">
              <input type="text" name="surname" placeholder="Nazwisko" />
            </div>
  
            <div class="form-group">
              <textarea name="message" placeholder="Wiadomość" rows="1"></textarea>
            </div>
  
            <button class="btn" type="submit">Wyślij</button> 
          </form>
        </div>
        <div class="bottom-line">
          <span class="bottom-line--copy">Copyright &copy; 2018</span>
          <div class="bottom-line--icons">
            <a href="#" class="btn btn--small"><img src="/static/images/icon-facebook.svg"/></a>
            <a href="#" class="btn btn--small"><img src="/static/images/icon-instagram.svg"/></a>
          </div>
        </div>
      </footer>
  </body>
{% endblock %}

charity/templates/charity/register.html
{% extends 'base.html' %}
{% load static %}
{% block container %}
    <header>{% include 'partials/nav.html' %}</header>
  <body>
    <section class="login-page">
      <h2>Załóż konto</h2>
      <form method="POST" action="/register/">
          {% csrf_token %}
        <div class="form-group">
          <input type="text" name="name" placeholder="Imię" />
        </div>
         <div class="form-group">
          <input type="text" name="surname" placeholder="Nazwisko" />
        </div>
        <div class="form-group">
          <input type="email" name="email" placeholder="Email" />
        </div>
        <div class="form-group">
          <input type="password" name="password" placeholder="Hasło" />
        </div>
        <div class="form-group">
          <input type="password" name="password2" placeholder="Powtórz hasło" />
        </div>

        <div class="form-group form-group--buttons">
          <a href="login.html" class="btn btn--without-border">Zaloguj się</a>
          <button class="btn" type="submit">Załóż konto</button>
        </div>
      </form>
    </section>

    <footer>
      <div id="contact" class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form>
          <div class="form-group form-group--50">
            <input type="text" name="name" placeholder="Imię" />
          </div>
          <div class="form-group form-group--50">
            <input type="text" name="surname" placeholder="Nazwisko" />
          </div>

          <div class="form-group">
            <textarea
              name="message"
              placeholder="Wiadomość"
              rows="1"
            ></textarea>
          </div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2018</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"
            ><img src="/static/images/icon-facebook.svg"
          /></a>
          <a href="#" class="btn btn--small"
            ><img src="/static/images/icon-instagram.svg"
          /></a>
        </div>
      </div>
    </footer>
  </body>
{% endblock %}

charity/templates/charity/user_profile.html
{% extends 'base.html' %}
{% load static %}
{% block container %}
      <head>
        <title>My Profile</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            background-color: #F5F5F1;
          }

          .container {
            max-width: 1000px;
            margin: 0 auto;
            padding: 20px;
            background-color: #FFFFFF;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
          }

          .profile {
            display: flex;
            align-items: center;
            margin-bottom: 20px;
          }

          .profile img {
            width: 100px;
            height: 100px;
            border-radius: 50%;
            margin-right: 20px;
          }

          .profile h1 {
            font-size: 30px;
            margin: 0;
          }

          .profile p {
            font-size: 22px;
            margin: 0;
            color: #888888;
          }

          .stats {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
            padding: 20px 120px;
          }


          .container2 {
            max-width: 1000px;
            margin: 0 auto;
            padding: 20px;
            background-color: #FFFFFF;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
            font-size: 22px;
          }

          .stats div {
            text-align: center;
          }

          .stats h2 {
            font-size: 32px;
            margin: 0;
          }

          .stats p {
            font-size: 26px;
            margin: 0;
            color: #888888;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="profile">
            <img src="https://via.placeholder.com/100x100" alt="Profile Picture">
            <div>
              <h1>{{ user.first_name }} {{ user.last_name }}</h1>
              <p>Email: {{ user.email }}</p>
            </div>
          </div>
          <div class="stats">
            <div>
              <h2>123</h2>
              <p>Liczba Worków:</p>
            </div>
            <div>
              <h2>456</h2>
              <p>Organizacje wsparte:</p>
            </div>
          </div>
            {% for donation in donations %}
                {% if user.id == donation.user_id %}
                    {% if not donation.is_taken %}
                    <div class="container2" id="donation_{{ donation.id }}">
                        <p>Liczba worków: {{ donation.quantity }}</p>
                        <p>Dla: {{ donation.institution.name }}</p>
                        <p>Kategorie: {% for category in donation.categories.all %}{{ category.name }}, {% endfor %}</p>
                        <p>Odebrano: {{ donation.pick_up_time }}</p>
                        <form method="post" action="{% url 'charity:take_donation' donation.id %}">
                            {% csrf_token %}
                            <button type="submit">Zabrano!</button>
                        </form>
                    </div>
                    {% endif %}
                {% endif %}
            {% endfor %}
            {% for donation in donations %}
                {% if user.id == donation.user_id %}
                    {% if donation.is_taken %}
                    <div class="container2" id="donation_{{ donation.id }}" style="opacity: 0.5;">
                        <p>Liczba worków: {{ donation.quantity }}</p>
                        <p>Dla: {{ donation.institution.name }}</p>
                        <p>Kategorie: {% for category in donation.categories.all %}{{ category.name }}, {% endfor %}</p>
                        <p>Odebrano: {{ donation.pick_up_time }}</p>
                        <form method="post" action="{% url 'charity:return_donation' donation.id %}">
                            {% csrf_token %}
                            <button type="submit">Cofnij!</button>
                        </form>
                    </div>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </div>a
      </body>
{% endblock %}

templates/base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  </head>
  <body>

    {% block container %}
    {% endblock %}


    <script src="{% static 'js/app.js' %}"></script>
  </body>
</html>

templates/partials/nav.html
<nav class="container container--70">
    {% if not user.is_authenticated %}
  <ul class="nav--actions">
    <li><a href="{% url 'charity:login' %}" class="btn btn--small btn--without-border">Zaloguj</a></li>
    <li><a href="{% url 'charity:registration' %}" class="btn btn--small btn--highlighted">Załóż konto</a></li>
  </ul>
    {% endif %}

    {% if user.is_authenticated %}
        <ul class="nav--actions">
          <li class="logged-user">
          Witaj {{ user.first_name }}!
            <ul class="dropdown">
                {% if user.is_superuser %}
                    <li><a href="{% url 'admin:index' %}">Panel Administratora</a></li>
                {% endif %}
                <li><a href="{% url 'charity:edit_profile' %}">Ustawienia</a></li>
                <li><a href="{% url 'charity:profile' %}">Profil</a></li>
                <li><a href="{% url 'charity:logout' %}">Wyloguj</a></li>
            </ul>
          </li>
        </ul>
    {% endif %}

  <ul>
    <li><a href="{% url 'charity:landingpage' %}" class="btn btn--without-border">Start</a></li>
    <li><a href="{% url 'charity:landingpage' %}#steps" class="btn btn--without-border">O co chodzi?</a></li>
    <li><a href="{% url 'charity:landingpage' %}#about-us" class="btn btn--without-border">O nas</a></li>
    <li><a href="{% url 'charity:landingpage' %}#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
    <li><a href="{% url 'charity:donation' %}" class="btn btn--without-border">Przekaż dary</a></li>
    <li><a href="#contact" class="btn btn--without-border">Kontakt</a></li>
  </ul>
</nav>